### ISSUE TITLE
There needs to be a way to override configuration files in a predictable order

### ISSUE THREAD

**Issue by ghost** [tristanfisher/yams#7]
YAMS needs a way to tier and override configuration attributes in a way that doesn't get in the way of pulling down upgrades.

This should work in the order of:
- Environmental variable
- (app specific variable files, e.g. boto's ~/.aws/{config, credentials} file
- class-overrides
- command line switches

**Comment by tristanfisher** [comment]
Ansible takes a per-setting get approach -- https://github.com/ansible/ansible/blob/a7231c220378554d44a611000bde2af2883fe064/lib/ansible/constants.py

this could be useful if populating the blueprint object with only the config+credentials it needs -- e.g. calling `dev_bp.config.aws` should not give access to the `core_users_bp.config` objects.  

The config items could then be implemented as properties, which would address the needs of issue.
